### ISSUE TITLE
Linter false positive for `should_use_compilers`?

### ISSUE THREAD

**Issue by nh13** [bioconda/bioconda-utils#1037]
See: https://github.com/bioconda/bioconda-recipes/actions/runs/13865436312/job/38803429081.  Job log is here: [job-logs.txt](https://github.com/user-attachments/files/19255005/job-logs.txt).

I copied the [`meta.yaml`](https://github.com/bioconda/bioconda-recipes/blob/6144f7b3397dac92a72036fe4981add6a50c6bef/recipes/fqgrep/meta.yaml) here:

```yaml
{% set version = "1.1.0" %}

package:
  name: fqgrep
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('fqgrep', max_pin="x") }}

source:
  url: https://github.com/fulcrumgenomics/fqgrep/archive/v{{ version }}.tar.gz
  sha256: 7be606f25f2241fc6d071276888cf7c82a8f8b4073dd5488e08a663e94715f48

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - rust >=1.60  
    - pkg-config
    - make
    - cmake
  host:
  run:

test:
  commands:
    - fqgrep --help

about:
  home: https://github.com/fulcrumgenomics/fqgrep
  license: MIT
  license_file: LICENSE
  summary: Search a pair of fastq files for reads that match a given ref or alt sequence

extra:
  recipe-maintainers:
    - nh13
```
