### ISSUE TITLE
pin linting considers patch files packages (regression by #188)

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#190]
Since the merge of #188, patches beginning with the name of a pinned package fail linting:

```yaml
source:
  patches:
    - boost_106400.patch
```

(Kudos to @nsoranzo for finding the cause)
