### ISSUE TITLE
automating labeling of broken packages

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-utils#232]
(continuing from https://github.com/bioconda/bioconda-recipes/issues/6637#issuecomment-348510372, cc @johanneskoester @mbargull)

To summarize https://github.com/bioconda/bioconda-recipes/issues/6637:

Currently, when we find a package to be broken, we bump the build number. Our reasoning for this was that conda would always try to install the latest build number and ignore earlier build numbers. However, this is not the case, and some situations conda installs earlier build numbers. Instead, we need to mark a package as broken so that it will not be installed. We can do this by adding the `broken` [label](https://docs.anaconda.com/anaconda-repository/2.32/user/using#using-labels-in-the-development-cycle) to the package instead of the default `main` label.

It would be nice to do this via bioconda-utils on travis, so that contributors could mark their packages themselves without requiring core members to manually mark it. Furthermore, it would also be useful to have a record of this in the recipe somehow in git.

I suspect this will be another key in `extra:`. What about:

```yaml
name: examplepkg
version: 1.0
build:
  number: 4
...
extra:
  add_labels:
    broken:
      - 
        version: 1.0
        build_number: 2
      - 
        version: 1.0
        build_number: 3
```

When merged into master, bioconda-utils will mark `examplepkg-1.0_2` and `examplepkg-1.0_3` as broken by adding the `broken` label if that is not already the case. If, in the future, we determine that build 3 should not be considered broken, they can be removed from the list and by doing so it will be re-labeled as the default `main` label:

```yaml
name: examplepkg
version: 1.0
build:
  number: 4
...
extra:
  add_labels:
    broken:
      - 
        version: 1.0
        build_number: 2
```

Furthermore, we can add additional labels using this mechanism. For example, our channel also currently has a `deprecated` label, which could be added the same way:
```yaml
name: examplepkg
version: 1.0
build:
  number: 4
...
extra:
  add_labels:
    broken:
      - 
        version: 1.0
        build_number: 2
    deprecated:
      - 
        version: 1.0
        build_number: 3
```
