### ISSUE TITLE
Build error using biocontainers with drone.io

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-utils#295]
Hi Team Bioconda,

I would like to use some Biocontainer containers in a CI code-testing pipeline. Our current CI system is drone.io but when I use the Biopython container  for testing I run into  the following error:

```
# build error
/bin/sh: base64: not found

# .drone.yml
pipeline:
  build:
    image: quay.io/biocontainers/biopython:1.70--np112py36_1
    commands:
      - python setup.py test
```

The build error happens immediately and suggests that `/bin/sh` is not being found which I thought was standard in all Docker images.  The most similar issue that  [I could find](https://github.com/drone/drone/issues/2296) was due to the user inadvertently overwriting the `$PATH`, however in my case I do not make any attempts to touch the PATH so it seems that '/bin/sh' is not a recognized part of the Docker path. 

I'm afraid I've run into the limits of my knowledge about container internals and I am hoping that one of the members of the core team might recognize this error and provide some tips on how to address this issue.

Thank You,
zach cp
