### ISSUE TITLE
Version pinning from conda_build_config.yaml doesn't seem to be enforced when testing the Kallisto package

### ISSUE THREAD

**Issue by Hogfeldt** [bioconda/bioconda-utils#529]
I'm trying to build the Kallisto package but when the tests are running I get a mismatch between the hdf5 header files and the library files. Here is the error message:
```
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.4, library is 1.10.5
	    SUMMARY OF THE HDF5 CONFIGURATION
	    =================================
...

Bye...
/home/fuan/miniconda3/envs/bioconda_recipe_gen/conda-bld/kallisto2_1557218788171/test_tmp/run_test.sh: line 7:  4458 Aborted                 (core dumped) kallisto quant t.fq -i t.idx --single -l 300 -s 2 -o tmp
Tests failed for kallisto2-0.45.0-hd5b5912_0.tar.bz2 - moving package to /home/fuan/miniconda3/envs/bioconda_recipe_gen/conda-bld/broken
```
At build time the conda environment uses the package `hdf5: 1.10.4-nompi_h3c11f04_1106 conda-forge` and at run time the conda environment uses the package `hdf5: 1.10.5-nompi_h3c11f04_1100 conda-forge`.
I find this strange since the hdf5 version should be pinned to `1.10.4` in the `conda_build_config.yaml` from conda-forge. 
When I look at the recipe from the output file, hdf5 is included in the `conda_build_config.yaml` and pinned to version `1.10.4`, but when looking at the `meta.yaml` I find the following:
```
# This file created by conda-build 3.10.6
# meta.yaml template originally from:
# /home/fuan/Documents/birc/bioconda_recipe_gen/bioconda-recipes/recipes/kallisto2, last modified Tue May  7 09:43:58 2019
# ------------------------------------------------

package:
    name: kallisto2
    version: 0.45.0
source:
    sha256: b32c74cdc0349c2fe0847b3464a3698da89212a507332a06291b6fc27b4e2305
    url: https://github.com/pachterlab/kallisto/archive/v0.45.0.tar.gz
build:
    string: hd5b5912_0
requirements:
    build:
        - autoconf 2.69 pl526h14c3975_9
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.3.9 hecc5488_0
        - cmake 3.14.3 hf94ab9c_0
        - curl 7.64.1 hf8cf82a_0
        - expat 2.2.5 hf484d3e_1002
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - krb5 1.16.3 h05b26f9_1001
        - libcurl 7.64.1 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 8.2.0 hdf63c60_1
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libuv 1.28.0 h516909a_0
        - m4 1.4.18 h14c3975_1001
        - make 4.2.1 h14c3975_2004
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - perl 5.26.2 h516909a_1006
        - rhash 1.3.6 h14c3975_1001
        - tk 8.6.9 h84994c4_1001
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    host:
        - hdf5 1.10.4 nompi_h3c11f04_1106
        - libgcc-ng 8.2.0 hdf63c60_1
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - zlib 1.2.11 h14c3975_1004
    run:
        - hdf5
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - zlib >=1.2.11,<1.3.0a0
test:
    files:
        - t.fa
        - t.fq
extra:
    copy_test_source_files: true
    final: true
```
It seems like the pinning of hdf5 isn't enforced in the run time environment and therefore conda just pick the latest version and then gets the wrong header files.

**Comment by dpryan79** [comment]
This is one of the few packages that sets `run_exports`: https://github.com/conda-forge/hdf5-feedstock/blob/master/recipe/meta.yaml#L61-L62 . I wonder if that's related to this.

**Comment by Hogfeldt** [comment]
As i understands it the documentation on `run_exports` (https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#export-runtime-requirements) hdf5 has a weak run export, which means that when hdf5 is added as a host requirement it should be added as a run requirement implicitly. 
I thought that maybe adding hdf5 as a run requirement, could interfere with the weak run export, so I have just tried to build kallisto with hdf5 only added as a host requirement. This doesn't work since hdf5 is now missing at run time. The output meta.yaml looks like this:
```
# This file created by conda-build 3.10.6
# meta.yaml template originally from:
# /home/fuan/Documents/birc/bioconda_recipe_gen/bioconda-recipes/recipes/kallisto2, last modified Tue May  7 13:15:48 2019
# ------------------------------------------------

package:
    name: kallisto2
    version: 0.45.0
source:
    sha256: b32c74cdc0349c2fe0847b3464a3698da89212a507332a06291b6fc27b4e2305
    url: https://github.com/pachterlab/kallisto/archive/v0.45.0.tar.gz
build:
    string: hd5b5912_0
requirements:
    build:
        - autoconf 2.69 pl526h14c3975_9
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.3.9 hecc5488_0
        - cmake 3.14.3 hf94ab9c_0
        - curl 7.64.1 hf8cf82a_0
        - expat 2.2.5 hf484d3e_1002
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - krb5 1.16.3 h05b26f9_1001
        - libcurl 7.64.1 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 8.2.0 hdf63c60_1
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libuv 1.28.0 h516909a_0
        - m4 1.4.18 h14c3975_1001
        - make 4.2.1 h14c3975_2004
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - perl 5.26.2 h516909a_1006
        - rhash 1.3.6 h14c3975_1001
        - tk 8.6.9 h84994c4_1001
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    host:
        - hdf5 1.10.4 nompi_h3c11f04_1106
        - libgcc-ng 8.2.0 hdf63c60_1
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - zlib 1.2.11 h14c3975_1004
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - kallisto version
    files:
        - t.fa
        - t.fq
extra:
    copy_test_source_files: true
    final: true
```
It looks like the weak run export doesn't work, since hdf5 isn't added as a run requirement.

**Comment by dpryan79** [comment]
It looks like you're correct, which suggests that this should be changed on conda-forge-pinning. Can you open an issue there and xref this? We're more likely to get input from someone at conda who know more about how this is really supposed to work that way.

**Comment by Hogfeldt** [comment]
Before opening an issue at conda-forge-pinning, I wanted to see if I could isolate the problem to the pinning in the `conda_forge_config.yaml`, but the pinning seems to work fine. 
I am using the following `meta.yaml` where hdf5 is only added as a requirement in host. By doing this the package should only be able to succeed the tests if the weak run export rule works.
```
{% set version = "0.45.1" %}

package:
  name: kallisto
  version: {{ version }}

source:
  url: https://github.com/pachterlab/kallisto/archive/v{{ version }}.tar.gz
  sha256: 2c97280c69991f995f77e7c8ab56ae5060329c90f7f0d7e9ca2f01dd50ee378f

build:
  number: 0
  script_env:
    - HDF5_DISABLE_VERSION_CHECK 

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - autoconf
    - automake
  host:
    - hdf5
    - zlib
  run:
    - zlib

test:
  files:
    - t.fa
    - t.fq
  commands:
    - kallisto version

about:
  home: "http://pachterlab.github.io/kallisto"
  license: BSD_2_Clause
  summary: Quantifying abundances of transcripts from RNA-Seq data, or more generally of target sequences using high-throughput sequencing reads.

extra:
  identifiers:
    - biotools:kallisto
    - doi:10.1038/nbt.3519
```
I am running conda-build in a little docker image (https://hub.docker.com/r/perhogfeldt/conda-build-mini) which only contains conda and a couple of conda packages (conda-build, conda-verify, conda-forge-pinning). 
When building the kallisto package in this image, without the `conda_build_config.yaml` file, the package builds and all tests succeeds, since the newest hdf5 package `hdf5: 1.10.5-nompi_h3c11f04_1100 conda-forge` is installed in both the build and the run environment. 
When I then include the `conda_build_config.yaml` file in a new instance of the same environment, the pinning works, so kallisto is build with the hdf5 package `hdf5: 1.10.4-nompi_h3c11f04_1106 conda-forge` but the weak run export rule also works, since the same hdf5 package is added to the run environment and the tests succeeds.
I guess the conclusion is, that the pinning and `run_exports` works as the documentation states. But something goes wrong when building the package via `bioconda-utils`.

I discovered that I was using an older version of bioconda-utils and thought maybe that could be the reason why `run_exports` doesn't seem to work. So I just updated from `0.15.10` to `0.15.12` and tried to build the above kallisto package. The build and tests seems to pass now, but when i look at the `meta.yaml` from the output archive file, I still think its a bit shady, since the version of the hdf5 package which is added to the run requirement is still unspecified.
Here is a copy of the output `meta.yaml`:
```
# This file created by conda-build 3.10.6
# meta.yaml template originally from:
# /home/fuan/Documents/birc/bioconda_recipe_gen/bioconda-recipes/recipes/kallisto2, last modified Tue May  7 14:47:24 2019
# ------------------------------------------------

package:
    name: kallisto2
    version: 0.45.1
source:
    sha256: 2c97280c69991f995f77e7c8ab56ae5060329c90f7f0d7e9ca2f01dd50ee378f
    url: https://github.com/pachterlab/kallisto/archive/v0.45.1.tar.gz
build:
    number: '0'
    script_env:
        - HDF5_DISABLE_VERSION_CHECK
    string: hb6a4e58_0
requirements:
    build:
        - autoconf 2.69 pl526h14c3975_9
        - automake 1.16.1 pl526_1003
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.3.9 hecc5488_0
        - cmake 3.14.3 hf94ab9c_0
        - curl 7.64.1 hf8cf82a_0
        - expat 2.2.5 hf484d3e_1002
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - krb5 1.16.3 h05b26f9_1001
        - libcurl 7.64.1 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 8.2.0 hdf63c60_1
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libuv 1.28.0 h516909a_0
        - m4 1.4.18 h14c3975_1001
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - perl 5.26.2 h516909a_1006
        - rhash 1.3.6 h14c3975_1001
        - tk 8.6.9 h84994c4_1001
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    host:
        - hdf5 1.10.4 nompi_h3c11f04_1106
        - libgcc-ng 8.2.0 hdf63c60_1
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - zlib 1.2.11 h14c3975_1004
    run:
        - hdf5
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - kallisto version
    files:
        - t.fa
        - t.fq
about:
    home: http://pachterlab.github.io/kallisto
    license: BSD_2_Clause
    summary: Quantifying abundances of transcripts from RNA-Seq data, or more generally
        of target sequences using high-throughput sequencing reads.
extra:
    copy_test_source_files: true
    final: true
    identifiers:
        - biotools:kallisto
        - doi:10.1038/nbt.3519
```

**Comment by Hogfeldt** [comment]
It seems like I was looking in the wrong output file, here is the right output meta.yaml.
```
# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/fuan/Documents/birc/bioconda_recipe_gen/bioconda-recipes/recipes/kallisto2, last modified Tue May  7 16:28:42 2019
# ------------------------------------------------

package:
    name: kallisto2
    version: 0.45.1
source:
    sha256: 2c97280c69991f995f77e7c8ab56ae5060329c90f7f0d7e9ca2f01dd50ee378f
    url: https://github.com/pachterlab/kallisto/archive/v0.45.1.tar.gz
build:
    number: '0'
    string: hb6a4e58_0
requirements:
    build:
        - autoconf 2.69 pl526h14c3975_9
        - automake 1.16.1 pl526_1003
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.3.9 hecc5488_0
        - cmake 3.14.3 hf94ab9c_0
        - curl 7.64.1 hf8cf82a_0
        - expat 2.2.5 hf484d3e_1002
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - krb5 1.16.3 h05b26f9_1001
        - libcurl 7.64.1 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 8.2.0 hdf63c60_1
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libuv 1.28.0 h516909a_0
        - m4 1.4.18 h14c3975_1001
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - perl 5.26.2 h516909a_1006
        - rhash 1.3.6 h14c3975_1001
        - tk 8.6.9 h84994c4_1001
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    host:
        - hdf5 1.10.4 nompi_h3c11f04_1106
        - libgcc-ng 8.2.0 hdf63c60_1
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - zlib 1.2.11 h14c3975_1004
    run:
        - hdf5 >=1.10.4,<1.10.5.0a0
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - kallisto version
    files:
        - t.fa
        - t.fq
about:
    home: http://pachterlab.github.io/kallisto
    license: BSD_2_Clause
    summary: Quantifying abundances of transcripts from RNA-Seq data, or more generally
        of target sequences using high-throughput sequencing reads.
extra:
    copy_test_source_files: true
    final: true
    identifiers:
        - biotools:kallisto
        - doi:10.1038/nbt.3519
```
Everything seems to work as it should I have just been using an old version of bioconda-utils.

**Comment by bgruening** [comment]
Was just about to look at this! Thanks for reporting back!

**Comment by mbargull** [comment]
> Thanks for reporting back!

Second that!

Last time I looked at the `run_exports` stuff was at the middle of last year or so and I found it a bit iffy/unreliable. I'm not sure how much `conda-build` has improved since then on that matter, so I can't really comment on whether it's something we can rely on by now.
Coincidentally, the `conda-build 3.10.6` that showed the reported issue was released around that time, too, so I'm not too surprised its output is broken. But at least I can confirm `conda-render` with `3.17.8` looks better
```yaml
    host:
        - libgcc-ng 8.2.0 hdf63c60_1
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - zlib 1.2.11 h14c3975_1004
        - hdf5 1.10.4 nompi_h3c11f04_1106
    run:
        - hdf5 >=1.10.4,<1.10.5.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
```
