### ISSUE TITLE
lint: detect potential duplicate keys due to selectors

### ISSUE THREAD

**Issue by mbargull** [bioconda/bioconda-utils#627]
xref: https://github.com/bioconda/bioconda-utils/pull/625#discussion_r350941678

Linting could detect
```yaml
source:
  - url: https://qwer  # [linux]
    sha256: 1234
  - url: https://asdf  # [osx]
    sha256: 5687
```
which renders for `linux` as
```yaml
source:
  - url: https://qwer  # [linux]
    sha256: 1234
    sha256: 5687
```
but should rather be
```yaml
source:
  - url: https://qwer  # [linux]
    sha256: 1234       # [linux]
  - url: https://asdf  # [osx]
    sha256: 5687       # [osx]
```
