### ISSUE TITLE
False positive lint `version_constraints_missing_whitespacewhen` for unequal constraint `!=` 

### ISSUE THREAD

**Issue by corneliusroemer** [bioconda/bioconda-utils#918]
`bioconda-utils lint` wrongly throws an error for a version constraint with `!=`:

```yaml
requirements:
  run:
    - fsspec !=2023.9.1
```

```
ERROR: recipes/nextstrain-cli/meta.yaml:45: version_constraints_missing_whitespace: Packages and their version constraints must be space sepa
```

This was noticed in https://github.com/bioconda/bioconda-recipes/pull/43160
